language: node_js
node_js: stable
sudo: false
install: true
os:
- linux
before_script:
- npm install
branches:
  only: master
cache:
  directories: node_modules
script:
- npm run tests.all
deploy:
  provider: firebase
  token:
    secure: YOUR ENCRYPTED token
env:
  global:
  - secure: PtPSrBEz3DCFNfMJsdVamXtPXtJfbvvDp2NHkGoSFTMB8splGYnW8T/FVrQ2vN+jcc0RUBJ7Gq2bSZjPpEuxPR2X/Xcq+VHEvpUoYlaFYVVIWHqgCDvvuro7nSgTWddp4uGJ56ynPMY6TicpsGKoAFZPiQ9OuC7FvMEXVdwabrjqeSKRffOd7yFCKhITrELzxrZ9cbGZhb+EB+WY/3ext9eZ7yDGbENLVpTla3D6Fw7t3rvm862K4PbO2LtH6eFlTxVUzn0MhFC3LUlT7ogydzRK8b1cqSgE3qT093FbyaF9rojAbMZvUf8VgJc1a4ZOvQW+12C8IiI9xN2r3qdqPYjHrQ0RqezV/R5EWLoTcpB3UW9A21M3i4QY+A+3NXGlM3y8oZ+W8FksIVXf2EyjLKnlBvTeigrdG9jNOlpLNzljl3NCC9wlPnuvwDxvyEVzEtKKCUNgBjEYknYt+5eMHKHVcNd7WahfrHu3IoVPn/ZTY6mIAq0KB931rr2HKCG99v4RiIDmAgdR0PpbSt2j/XgkH/p4xuMrpKSxx+YBYTXmD8qavNtNTYgp3b1Kz7gQZVu5JUwKOBSbFx+bZOvBjlwzkPbnym9zV2sT7TVraYkpQFhAApXlQ0tKYi79tArN5f6G8zLR1vdk+Qrf3IkxoQbWbgQdUx7z8S8cPoMabCE=
  - secure: u7uh919gSAjrFMG53aMmFNfWR2Gq1c8d7VzZWwjg/4D9AEuU1mPH1U+iNpszpU8WbIe6ptWFNr6UJTcoLgH8c2yExK47TyQO9JYIkk0jP61HwPkC8PraW2KmkoPjFPks2SJhEIj7nliey31kao2rwTLnLVucXeh/QQpwt+eLY8uDUnIgtI/p2eyZDngXfEfL68SOZ8cUROOunFfCj+ns8z4ztw8DqE/86yn0L/8rvZ+Mh5Qkr0A4sAg4iKZ4DJ2gf0QPe0ZmF0EQNqK9L6GOZ50hkzbRa3PTdcSaP0huD/FVM0GzlsOcc2pknyXX9qQLFKDNz82kYIe49YTmu/TQYQoMDl7h+mB5H0IyJ1q+EjhhH+aCJJ+CKjT72Ay9v35GFNEys3jWr5juzMhANd0KaerotVu/PDWUZQOuKtQkglkgNSM9jEmSQMkaJJez8v+maUHYUgoq2+eJ2/LZ600+bECdSQGR58k17yXowBAzf2SliSZ/AsVgeU+vQWnFUvyu2Hwm/66hr8fMpbmg4QTFoeTiUnz6tCJx70s7+ltIIpQDlAV1602gFNyCKmgkFqYsRnCf+1wJfwUwWau9RX9+72Td5bNFqIpFSCenRdqmfOz0F2ICSSuwpsgsWlTdXsBXCpguZOGOphH7eOreQTVjOsiyPKbUR8C+VyGgYwGkJk0=
  - secure: XlKhMU3lY1OQlxZRCXs67BgSddxs5SDtiA2Mh2GdE+2DRj0Swk7RK995nTMdMZd/JoqVyuT816CjymseRPieFSjDVk8yirZN57BlN58y8LeypBVrEF0F+szFPotRRbqpcCn92eelwuapvTn6EH564PTPnY7Z9IrqJIp9F8to4rQW6zGK8GkO8GcYONFWrOSMhQ14eRxH2gRA8FqPEOAT3Wt66PDlnhpYqKp+HQIpK/7hBMBEWfQ+EegqTrxH8EgoY3ijHMEaF471WuV6YAcX2LfrX085AQzCJml15j+JXTKoumEVagDas4JYYn8zAyJTni5GAQ1ANZjkKWLNKzQDc/QQPp5c5jJdVW1ufuSz3zOhpI+SwKWI3Ph/O7StVQnjoTGzmeGPeOO3dRR++x0qCy4ze2Lrhs/RiCFPJL17fdiKNX5iTU76Ti0122XJhpukGPspyfgZY9kjd1yU74fWIHCYciDiXyvSNocntXWD4eyu9wsxSV7erEtbK1+11E6H7dGbVUPO0ePH2N2pqo6o4s2xKUcsWBsrgv9WMjmUKWdKtNct7i+eCFdPsap7Agl7qTPY7pvc25AnyBnLi1UX/hI3t2EVLVzZ3DFa04NrLe4PSolDe7kRCUoE816MTorsDfh5XVdxkfp6WINaCyT6clx+YNfj6QaJS4j8hu5Yu/8=
