language: node_js
node_js: stable
sudo: false
install: true
os:
- linux
before_script:
- npm install
branches:
  only: master
cache:
  directories: node_modules
script:
- npm run tests.all
deploy:
  provider: firebase
  token:
    secure: VYywOQDfHrjtyqI1aHSbn/HzbWNhwIHRXiaYJLYX1CqUSCgxR23JVnNeHvQ8XpZHmAVwjBiC7IrUYx+PLUQi5LTeYnNo5v2wTBAOg67+51UFM8shUKhlaNwLfgsgvrvM1GZHgoLHrH9Sf6cQRIQXNgLDAAv7BLjplZqFVicBsZORy7lr0Qx1o1Q1yc2NOphsKlayLK2XP8fZOD7UGdCc9D5DH5qLToqppvhwCbIxejRvVpH0KcTAmqVl2Qt1jhfmrEgRCpM0MSQ82KUkKT6moG3KVh1NEcvWlwoCxP0i8grETVJiRYeUlGQw7UDSksQG4T48i+0SWNkjbVfK94FpsMfnlqsKGSwl+jae0ouguAKYVckEaCEzWt4bRl7/eMyQ/aKTVhqCC3BJenNJnyRQ/HndmU3Z7OYGwX3taRuzrKt2829p6bb30Yv0hCWO4VwRjpyydulolZxbWyKg/9skIUuJiRaNrThl0rx8LANflSCg1hfUhQ1WOKixtQFWvQIhpYt98BehPXq1k3H6pkUa16mKsK3MFqoPOmFl5lxGcREui0AdlL+kyWQU5xK7wH+ffyc3ZydoS63tccTkvPfU4TjciBPODXbSqtb5kCUP2Fxkta7JLwHBln0U3wK/lRH3CWgfGGrAH/9Sn64hxTfUerkt+/07a/VEDFbLqya/zIE=
    